# Generated by Django 6.0.3 on 2026-04-03 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declaracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('informe_rendimentos', 'Informe de Rendimentos'), ('recibo_medico', 'Recibo Médico'), ('boleto_escola', 'Comprovante de Educação'), ('outros', 'Outros')], max_length=30)),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('status_processamento', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=15)),
                ('dados_extraidos', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('declaracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='declaracao.declaracao')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
