# Generated by Django 6.0.3 on 2026-04-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('preco_anual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_declaracoes', models.IntegerField(help_text='-1 = ilimitado')),
                ('chat_ilimitado', models.BooleanField(default=False)),
                ('permite_upload_docs', models.BooleanField(default=False)),
                ('permite_ganho_capital', models.BooleanField(default=False)),
                ('permite_exterior', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
