# Generated by Django 6.0.3 on 2026-04-03 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistente', '0001_initial'),
        ('declaracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='declaracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='declaracao.declaracao'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='assistente.conversa'),
        ),
    ]
