# Generated by Django 6.0.3 on 2026-04-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_verificacao_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilfiscal',
            name='tem_dividas',
            field=models.BooleanField(default=False),
        ),
    ]
