# Generated by Django 6.0.3 on 2026-04-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BemDireito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código Receita Federal', max_length=10)),
                ('discriminacao', models.TextField()),
                ('valor_anterior', models.DecimalField(decimal_places=2, default=0, help_text='Saldo em 31/12 do ano anterior', max_digits=15)),
                ('valor_atual', models.DecimalField(decimal_places=2, help_text='Saldo em 31/12 do ano-base', max_digits=15)),
            ],
            options={
                'verbose_name': 'Bem ou Direito',
                'verbose_name_plural': 'Bens e Direitos',
            },
        ),
        migrations.CreateModel(
            name='Declaracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_base', models.IntegerField()),
                ('modelo', models.CharField(blank=True, choices=[('simplificado', 'Simplificado'), ('completo', 'Completo')], max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em Revisão'), ('pronta', 'Pronta para Envio'), ('entregue', 'Entregue à Receita')], default='rascunho', max_length=20)),
                ('ir_devido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ir_retido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, help_text='Negativo = restituição. Positivo = imposto a pagar.', max_digits=12, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Declaração',
                'verbose_name_plural': 'Declarações',
            },
        ),
        migrations.CreateModel(
            name='Deducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dependente', 'Dependente'), ('saude', 'Despesas Médicas/Saúde'), ('educacao', 'Educação'), ('inss', 'Previdência Social (INSS)'), ('pgbl', 'Previdência Privada (PGBL)'), ('pensao_paga', 'Pensão Alimentícia Paga'), ('livro_caixa', 'Livro-Caixa')], max_length=20)),
                ('descricao', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cpf_cnpj_beneficiario', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Dedução',
                'verbose_name_plural': 'Deduções',
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('parentesco', models.CharField(choices=[('conjuge', 'Cônjuge/Companheiro(a)'), ('filho', 'Filho(a)/Enteado(a)'), ('pai_mae', 'Pai/Mãe'), ('avo', 'Avô/Avó'), ('irmao', 'Irmão/Irmã'), ('menor_guarda', 'Menor sob Guarda/Tutela'), ('incapaz', 'Incapaz sob Tutela/Curatela')], max_length=20)),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
            },
        ),
        migrations.CreateModel(
            name='GanhoCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bem', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField()),
                ('data_alienacao', models.DateField()),
                ('custo_aquisicao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isento', models.BooleanField(default=False)),
                ('motivo_isencao', models.CharField(blank=True, max_length=200)),
                ('darf_recolhido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ganho de Capital',
                'verbose_name_plural': 'Ganhos de Capital',
            },
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salario', 'Salário/Pró-labore'), ('aluguel', 'Aluguéis'), ('autonomo', 'Trabalho Autônomo'), ('pensao_recebida', 'Pensão Alimentícia Recebida'), ('aposentadoria', 'Aposentadoria/Pensão INSS'), ('rural', 'Atividade Rural'), ('exterior', 'Rendimentos do Exterior'), ('outros_tributaveis', 'Outros Tributáveis'), ('isento', 'Isento / Não Tributável'), ('exclusivo_fonte', 'Tributado Exclusivamente na Fonte')], max_length=30)),
                ('fonte_pagadora_nome', models.CharField(max_length=200)),
                ('fonte_pagadora_cnpj_cpf', models.CharField(blank=True, max_length=20)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ir_retido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inss_retido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Rendimento',
                'verbose_name_plural': 'Rendimentos',
            },
        ),
    ]
