# Generated by Django 6.0.3 on 2026-04-03 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declaracao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bemdireito',
            name='declaracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bens', to='declaracao.declaracao'),
        ),
        migrations.AddField(
            model_name='deducao',
            name='declaracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducoes', to='declaracao.declaracao'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='declaracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='declaracao.declaracao'),
        ),
        migrations.AddField(
            model_name='ganhocapital',
            name='declaracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganhos_capital', to='declaracao.declaracao'),
        ),
        migrations.AddField(
            model_name='rendimento',
            name='declaracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimentos', to='declaracao.declaracao'),
        ),
        migrations.AlterUniqueTogether(
            name='declaracao',
            unique_together={('usuario', 'ano_base')},
        ),
    ]
