# Generated by Django 6.0.3 on 2026-04-03 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracao', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemdireito',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('importado', 'Importado (declaração anterior)'), ('documento', 'Extraído de documento')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='deducao',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('importado', 'Importado (declaração anterior)'), ('documento', 'Extraído de documento')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='dependente',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('importado', 'Importado (declaração anterior)'), ('documento', 'Extraído de documento')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='rendimento',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('importado', 'Importado (declaração anterior)'), ('documento', 'Extraído de documento')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='ImportacaoDeclaracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/')),
                ('dados_brutos', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de revisão'), ('revisado', 'Revisado'), ('aplicado', 'Aplicado')], default='pendente', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('declaracao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='importacao', to='declaracao.declaracao')),
            ],
            options={
                'verbose_name': 'Importação de Declaração',
                'verbose_name_plural': 'Importações de Declaração',
            },
        ),
    ]
