# Generated by Django 6.0.3 on 2026-04-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracao', '0003_bemdireito_origem_deducao_origem_dependente_origem_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='declaracao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='declaracao',
            name='cpf_titular',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AddField(
            model_name='declaracao',
            name='is_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='declaracao',
            name='nome_titular',
            field=models.CharField(default='Titular Principal', max_length=200),
        ),
    ]
