# Generated by Django 6.0.3 on 2026-04-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracao', '0004_alter_declaracao_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passo', models.IntegerField(choices=[(1, 'Passo 1'), (2, 'Passo 2'), (3, 'Passo 3'), (4, 'Passo 4'), (5, 'Passo 5'), (6, 'Passo 6')], unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('url_youtube', models.URLField(blank=True, help_text='URL do vídeo no YouTube. Deixe em branco para ocultar.')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vídeo de Ajuda',
                'verbose_name_plural': 'Vídeos de Ajuda',
                'ordering': ['passo'],
            },
        ),
        migrations.AlterField(
            model_name='importacaodeclaracao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de revisão'), ('processando', 'Processando PDF'), ('revisado', 'Revisado'), ('aplicado', 'Aplicado'), ('erro', 'Erro na leitura')], default='pendente', max_length=20),
        ),
    ]
